AOSSIE-Org/PictoPy

UI/script.js
UI/styles.css

When user will click on photo then enlarged image will be open with blur background.

User click on photo event handled by adding code in script.js

---

README.md

I have made a simple desktop application named PictoPy using Python and the Tkinter library. PictoPy allows users to select and display images from their computer. Upon selecting an image, it shows the image along with its file path and performs basic object recognition to identify objects within the image. The detected objects are then listed in the user interface. Additionally, there's a 'Quit' button to exit the application.

Feature Addition: Basic Image Viewer Implementation

---

backend/app/config/settings.py
backend/app/database/albums.py
backend/app/database/images.py
backend/app/routes/albums.py
backend/app/routes/images.py
backend/app/utils/classification.py
backend/app/utils/metadata.py
backend/app/utils/wrappers.py
backend/main.py
backend/requirments.txt
backend/temp.py

1. Added  basic album logic functionality, The schema for album is 
```
album_name, photo paths array, description (optional and can edit), timestamp it was created(optional, may remove)
```
Operations are available on albums such as delete/create albums, add/remove photos from album, change its description
Wrapper functions are now used to check if the album and photos exist
2. Refined the get requests , removed the payload  in the FastAPI params to match the HTTP/s spec: 
https://stackoverflow.com/questions/978061/http-get-with-request-body
Now Query strings are used instead from the url which makes the request.

add album logic, change get requests format

---

docs/frontend/gallery-view.md
docs/frontend/setup.md
docs/frontend/state-management.md
docs/frontend/ui-components.md
frontend/src/Config/Backend.ts
frontend/src/components/Album/Albumpick.tsx
frontend/src/components/Album/ImageSelection.tsx
frontend/src/controllers/SetupController.tsx
frontend/src/hooks/AlbumService.ts
frontend/src/hooks/UseVideos.ts

Key changes:
- Refactored useFetchAllImages and useAddMultipleImages hooks into AlbumService
- Updated ImageSelection component to use the refactored hooks
- Fixed type issues with allImages in ImageSelection
- Removed duplicate code from UseVideos
- Minor adjustments to imports in various components

Fix: Import and type errors

---

backend/main.py

FastAPI depricated the use of on_event function and instead replaced it with lifespans.

updated the fastAPI backend with latest specifications of lifespans

---

README.md
docs/frontend/setup.md
frontend/src-tauri/tauri.conf.json

This PR enhances the documentation and configuration for building the Tauri app by adding essential instructions on setting up signing keys, along with updates to `tauri.conf.json` for better alignment with the current setup.
1. **Documentation Update**
- Added a new section detailing the steps to add signing keys before running the build command, addressing a previously missing requirement in the setup process.
- Provided example signing keys in the documentation to allow users to bypass the full signing key generation process, streamlining setup for new users and reducing potential configuration errors.
2. **Configuration Update**
- Modified `tauri.conf.json` to align with current usage patterns.
- Added a `pubkey` configuration in `tauri.conf.json` that matches the example keys …

Closes #51 : Tauri App Build Documentation and Configuration 

---

README.md
docs/frontend/setup.md
frontend/Dockerfile

This update introduces Docker support for the frontend of the PictoPy project, ensuring that the application can be consistently built and run in a containerized environment. In addition, the documentation has been updated to provide clear instructions on how to build the Docker image and set up necessary Tauri signing keys.
- The frontend of the project has been containerized using Docker.
- A `Dockerfile` has been created to allow for the easy creation of a Docker image for the frontend.
- The Docker container includes all the necessary dependencies and configurations to run the frontend in a consistent and isolated environment.
The following updates were made to the project documentation to guide developers on how to build the Docker image:
To build the Docker image, use the following …

Containerizing the Frontend with Docker and Updating Documentation

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature.yml

This PR adds three issue templates to standardize and streamline the process of creating and managing issues in the repository. The templates cover the following categories:
- Fixes: #56 
<details>
<summary> tested </summary>
</details>
<details>
<summary> screenshots </summary>
</details>

Add Issue Templates for Bug Reports, Documentation Updates, and Feature Requests

---

frontend/src/components/AITagging/FilterControls.tsx

The expected behavior should be that we can scroll the dropdown menu
https://github.com/user-attachments/assets/f45fadbc-c4b1-4192-9578-966c22ad73da

Fixes #86 Now Dropdown menu is scrollable and we can view all the tags 

---

frontend/src/components/Media/MediaView.tsx

fixes: #45 
Demo Video: 
https://github.com/user-attachments/assets/1836d77d-01d1-4994-a659-afe246723a09

feat: implement left and right arrow key navigation

---

frontend/src/layout/main.tsx

fixes: #105 The outer scrollbar has been removed to declutter the UI and enhance usability.

fixed the double scroll-bar issue

---

frontend/src/components/Navigation/Navbar/Navbar.tsx

Fix: navbar broken semantics

---

backend/app/facecluster/facecluster.py

This PR introduces significant improvements to the face clustering implementation, focusing on performance, type safety, and maintainability.
1. Custom TTL Cache Implementation
- Added time-based cache expiration
- Implemented LRU eviction strategy
- Thread-safe cache operations
- Automatic cache cleanup
2. Performance Optimizations
- Vectorized NumPy operations for distance calculations
- Reduced memory allocations
- Optimized batch processing
- Improved database operations
3. Type System Enhancements
- Added comprehensive type hints
- Implemented generic type support
- Added NumPy type annotations
- Improved static analysis capabilities
4. Code Quality Improvements
- Added comprehensive documentation
- Implemented proper error handling
- Added input validation
- Improved code …

Face Clustering Optimization and Cache Implementation

---

.github/workflows/merge.yml
frontend/package-lock.json

A github action would run whenever a PR is reviewed which would check is it possible to build the frontend or not

added workflow to check frontend build

---

frontend/src/components/AITagging/AIgallery.tsx
frontend/src/components/Album/ImageManagementDialog.tsx

minor bug fix in tanstack branch

---

README.md
frontend/scripts/setup_env.sh
frontend/scripts/setup_win.ps1

I've added script to setup this project on windows, improved linux script and updated readme.md making it more convenient to setup their project on both platforms.
This PR fixes #171

Added windows setup script

---

backend/app/ner/haarcascade_frontalface_default.xml
backend/app/ner/test.py

If a person types two names, the system will create embeddings for both individuals. The NER model will extract the names from the input to feed into the OpenCV model for face recognition.
If no face is detected, embeddings will not be created.
This means that the system only generates embeddings when a face is detected; if no face is found, it skips the embedding creation process.

Updated test file for the enhanced NER model to analyze faces.

---

frontend/src/components/Navigation/Sidebar/Sidebar.tsx

Sidebar UI Update

---

frontend/src/components/Navigation/Sidebar/Sidebar.tsx

Reverts AOSSIE-Org/PictoPy#181

Revert "Sidebar UI Update"

---

frontend/src/components/Media/MediaView.tsx
frontend/src/components/ui/PaginationControls.tsx
frontend/src/components/ui/pagination.tsx

https://github.com/user-attachments/assets/d6e89e12-4bea-4c5d-9ef7-30d29212d2b7

Cursor_update

---

frontend/src/components/Album/Album.tsx

There seems to be error coming after merge from #163, which is now fixed. Needs urgent merge @Pranav0-0Aggarwal

error fixed due to merge

---

backend/app/database/albums.py
backend/app/routes/albums.py
frontend/api/api-functions/albums.ts
frontend/src/components/Album/Album.tsx
frontend/src/components/Album/AlbumCard.tsx
frontend/src/components/Album/AlbumForm.tsx
frontend/src/types/Album.ts

hidden_album feature added

---

.gitignore
backend/.gitignore
backend/dist/README.md

This is with regard to the error pointed by @Karn-x7 and @ParagGhatage that npm run tauri dev was giving error after merging #271 
The error is fixed now.

Added fix for failing dev command.

---

frontend/src/components/VideoPlayer/NetflixStylePlayer.tsx

This PR introduces several enhancements and fixes for video playback:
- **Current Video Time Tracking:** The video player now tracks and displays the current playback time in real-time.
- **Duration Visibility:** The total duration of the video is now visible to the user.
- **Seek Functionality:** Users can now slide the progress bar to jump to a specific timestamp in the video.
- **Resolved Video Lagging Issue:** Implemented video auto-preloading to ensure smoother playback and reduce buffering delays.
These changes significantly improve the user experience by enhancing control over video playback and eliminating lag issues.
- Verified that the current time updates correctly during playback.
- Ensured the duration is accurately displayed.
- Tested the seek bar to confirm seamless video …

Added Video Time Tracking, Seek Functionality, and Preloading Fix (SR No. - 5 )

---

backend/app/utils/memory_monitor.py
backend/app/utils/onnx_manager.py
backend/app/yolov8/YOLOv8.py
backend/requirements.txt
backend/tests/test_onnx_manager.py

Addresses memory leaks in ONNX Runtime sessions during image processing operations by implementing proper session management and monitoring.
- ✨ Added `onnx_manager.py` with context manager for ONNX sessions
- 🔧 Modified YOLOv8 implementation to use session context manager
- 📊 Added memory monitoring utilities
- ✅ Added unit tests for ONNX session management
- 📦 Updated requirements.txt with psutil dependency
- Ran memory leak tests with multiple iterations
- Verified proper session cleanup
- Tested with batch image processing
- All existing tests passing
Fixes #335 
Initial testing shows:
- Reduced memory footprint during batch processing
- More predictable resource cleanup
- No significant impact on inference speed

🐛 Fix: Implement ONNX Session Management to Prevent Memory Leaks (S.R No: 9)

---

project_structure.txt

fixes #377 
This PR adds project_structure.txt to document the overall directory structure of the project.
🔹 Purpose:
->Provides a clear overview of the backend and frontend directory structure.
->Helps new contributors understand the file organization.
->Acts as a quick reference for project navigation.
🔹 Changes:
->Added project_structure.txt listing all key files and folders.
🔹 Screenshots:

Added project_structure.txt for better project understanding (SR No. - 13)

---

backend/app/facenet/facenet.py
backend/app/facenet/preprocess.py
backend/app/routes/facetagging.py
backend/app/utils/classification.py
backend/app/yolov8/YOLOv8.py
backend/app/yolov8/utils.py

I researched many models , large , medium etc but nano model might not be accurate but it will be good for a great user experience as it uses less resources and it is much faster, choosing a higher accurate model is tradeoff between user experience and accuracy. Also large models will make app heavy use more resources so only small amount of people will be able to experience the ai tagging feature , so I've kept yolov8n model.
I have added an unkown label and changed few paramaters to increase bit of accuracy and reduce wrongly classified images, though it does not drastically increase accuracy , its a minor change.
Currently model can categorize image just in these categories:
```python
class_names = ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', …
```

Face accuracy

---

README.md

my first contribution for open source project !!

Fixed typo in README: changed 'makes sure' to 'make sure'

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml

Issue number : #356
Issue Description :
"Updating issue template to add few more checklists."
Checklist added :
-Have you updated the docs for it?
-Have you added unit tests?
-Have your made sure unit tests pass?
-Have you made sure code formatting is correct?
Changes made on : 
- bug.yml
- feature.yml
On bug.yml :
On feature.yml :
and Changes :
on bug.yml:
and on feature.yml:

Updated issue template with submission checklist. [Sr. No - 20]

---

frontend/src/App.css

Fixed issue#384: Light Mode Toggle fix

---

.github/workflows/merge.yml
frontend/src/main.tsx

This pull request includes updates to the `.github/workflows/merge.yml` file to optimize the CI workflow. The most important changes include adding caching for Rust dependencies, cleaning up comments, and improving workflow configuration for better readability and efficiency.
* [`.github/workflows/merge.yml`](diffhunk://#diff-bdb37b2ad65e049a0fc043e88813fdcf7ca0118abc11d99bbda676adfcbbb5a1L37-R56): Added a caching step for the Cargo registry and build artifacts to speed up subsequent builds.
* The cache will be invalidated only when there are changes to the cargo.lock file or the cargo.toml file. 
* The time improvements are as follows:
- **MacOS**:  (4 min 39 s) to (2 min 10 s)
- **Ubuntu**:  (5 min 38 s) to  (2 min 21 s)
- **Windows**:  (11 min 49 s) to (4 min 23 s)
* This PR will save …

Added caching in the PictoPy-build-check workflow [Sr. No. 26]

---

mkdocs.yml

Reverts AOSSIE-Org/PictoPy#451

Revert "fix(docs): Replaced favicon with transparent icon (#446)"
